Algoritmo "Exemplo2"
// Lógica de Programação
// Professor: Marcos Monteiro 
// Descrição   : Imprimir o nome e endereço
// Autor(a)    : Alberes Silva
// Data atual  : 7/11/2022
Var
nome: caractere
endereco: caractere

Inicio
escreva ("Digite o seu nome: ")
leia (nome)
escreva ("Digite o seu endereço: ")
leia (endereco)

escreva("O meu nome é " + nome + " e o meu endereço é " + endereco)

Fimalgoritmo