Algoritmo "ExemploSE"
// Lógica de Programação
// Professor: Marcos Monteiro 
// Descrição   : SE
// Autor(a)    : Alberes Silva
// Data atual  : 7/11/2022
Var
nome: caractere
salario: real


Inicio
escreva("Digite o nome: ")
leia(nome)
escreva("Digite o salário: ")
leia(salario)
se(salario>1200)entao
escreval(nome," seu salário é maior que o salário mínimo!!!")
fimse


Fimalgoritmo