Algoritmo "Exercicio03"
// Lógica de Programação
// Professor: Marcos Monteiro 
// Descrição   : Saldo bancário
// Autor(a)    : Alberes Silva
// Data atual  : 7/11/2022
Var
saldoInicial,deposito,saldoAtual:real


Inicio
saldoInicial<-1000,00
escreva("Valor do depósito: ")
leia(deposito)
saldoAtual<-saldoInicial + deposito
escreval("O Saldo inicial é R$ ",saldoInicial," o depósito foi R$",deposito," e o saldo atual é R$",saldoAtual)

Fimalgoritmo