Algoritmo "Exercicio05"
// Lógica de Programação
// Professor: Marcos Monteiro 
// Descrição   : Maior idade
// Autor(a)    : Alberes Silva
// Data atual  : 7/11/2022
Var
idade: inteiro


Inicio
escreva("Digite a idade: ")
leia(idade)
se(idade<18)entao
escreval("Menor de idade")
senao
se((idade>=18) E  (idade<60))entao
escreval("Adulto")
senao
escreval("Idoso")
fimse
fimse


Fimalgoritmo