Algoritmo "Exercicio1"
// Lógica de Programação
// Professor: Marcos Monteiro 
// Descrição   : Programa para receber Nome, peso e altura
// Autor(a)    : Alberes Silva
// Data atual  : 7/11/2022
Var
nome: caractere
peso, altura:real


Inicio
escreva("Digite o seu nome: ")
leia(nome)
escreva("Digite o seu peso: ")
leia(peso)
escreva("Digite a sua altura: ")
leia(altura)
escreva("O meu nome é ",nome , ",o meu peso é ", peso ,"kg e a minha altura é ", altura)


Fimalgoritmo