Algoritmo "Interrompa"
// Lógica de Programação
// Professor: Marcos Monteiro 
// Descrição   : Teste de comando interrompa
// Autor(a)    : Alberes Silva
// Data atual  : 9/11/2022
Var
j:inteiro


Inicio
escreval("Imprimindo de 1 a 10 repita até:")
j<-1
repita
escreval(j)
j<-j+1
se j=5 entao
interrompa
fimse
ate j>10
escreval("Executando após um INTERROMPA J=",j)


Fimalgoritmo