Algoritmo "semnome"
// Lógica de Programação
// Professor: Marcos Monteiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 9/11/2022
Var
idade,j:inteiro


Inicio

j<-1
enquanto (j< 5) faca
escreval("Digite a sua idade: ")
leia(idade)
se (idade<18)
idadeMenor=idade+1
senao
se (idade>60)
idadeMaior=idade+1
senao

j<-j+1



fimenquanto



Fimalgoritmo