Algoritmo "Vetor"
// Lógica de Programação
// Professor: Marcos Monteiro 
// Descrição   : Nome de Alunos
// Autor(a)    : Alberes Silva
// Data atual  : 13/11/2022
Var
aluno: vetor[1..5]de caractere
i: inteiro //indice do vetor

Inicio
para i<-1 ate 5 faca  //laço de cadrastro
escreva("Digite o nome do ",i,"º aluno: ")
leia(aluno[i])
fimpara
para i<-1 ate 5 faca  //laço de impressão
escreval("Nome do ",i,"º aluno: ",aluno[i])
fimpara

Fimalgoritmo